name: Unit Test CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    env:
      MONGO_URL: ${{ secrets.MONGO_URL }}
      COOKIE_NAME: ${{ secrets.COOKIE_NAME }}
      COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
      VALIDATION_KEY: ${{ secrets.VALIDATION_KEY }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_USERNAME: ${{ secrets.REDIS_USERNAME }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v1.0.0 # ssh 접속하는 오픈소스
        with:
          host: ${{ secrets.REMOTE_HOST }} # 인스턴스 IP
          username: ${{ secrets.REMOTE_USER }} # 우분투 아이디
          key: ${{ secrets.REMOTE_PRIVATE_KEY }} # ec2 instance pem key
          port: ${{ secrets.REMOTE_PORT }} # 접속포트
          script: | # 실행할 스크립트
            sudo -s
            cd /home/ubuntu/grinergy-back-v2
            git pull origin dev
            pm2 kill
            npm i --force
            npm run start
